### PR TITLE
bump version after 7.9.1 release

### PR DESCRIPTION
**Pull request by Mpdreamz**

### CODE REVIEW

**Comment by Mpdreamz** [comment]
Noticed the `v7.9.1` label was called `v7.9.1` so renamed it. Got a bit cross eyed looking for it 🐱

**Review by bpintea — APPROVED** [review]
LGTM, thx!

**Comment by bpintea** [comment]
> Noticed the `v7.9.1` label was called `v7.9.1` so renamed it. 

... to `v7.9.1`? 👀

**Comment by Mpdreamz** [comment]
> > Noticed the `v7.9.1` label was called `v7.9.1` so renamed it.
> 
> ... to `v7.9.1`? 👀

LOL did it again, it was called `v.7.9.1` previously.

**Comment by bpintea** [comment]
> LOL did it again, it was called `v.7.9.1` previously.

Hehe, that was my first guess. Thanks for fixing it.

**Pull request merged**
